// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Models.Settings.Services.Validators;

namespace WebApplication1.Models
{
    [Table("User")]
    public partial class User
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        [PreventBadWords(ErrorMessage = "Don't use bad language in Firstname")]
        public string FirstName { get; set; }
        [StringLength(50)]
        [Unicode(false)]

        [PreventBadWords(ErrorMessage = "Don't use bad language. You will be reported to police")]
        public string LastName { get; set; }
        [Column(TypeName = "date")]
        [DataType(DataType.Date)]
        public DateTime? DateOfBirth { get; set; }
        [Required]
        [StringLength(10)]
        [Unicode(false)]
        public string Pan { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Address { get; set; }
        [StringLength(1)]
        [Unicode(false)]
        public string Gender { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string MobileNumber { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Email { get; set; }
        [Required]
        [Column(TypeName = "text")]
        public string Comments { get; set; }
    }
}